# Generated by Django 3.2 on 2021-05-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "Consignee",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Consignee"
                    ),
                ),
                (
                    "company_invoice_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company Invoice No",
                    ),
                ),
                (
                    "consignee_order_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Consignee Order No",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Sender"
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Receiver"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Currency"
                    ),
                ),
                (
                    "AWB_no_first",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="AWB No First",
                    ),
                ),
                (
                    "AWB_no_second",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="AWB No Second",
                    ),
                ),
                (
                    "from_in_base",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="From"
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="To"
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Via"
                    ),
                ),
                (
                    "chargeable_weight",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chargeable Weight",
                    ),
                ),
                (
                    "gross_weight",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Gross Weight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mandatory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("sell", "Sell"), ("buy", "Buy")],
                        default="buy",
                        max_length=255,
                        verbose_name="Agency",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Agency"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Carrier"
                    ),
                ),
                (
                    "airfreight",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Airfreight"
                    ),
                ),
                (
                    "airway_bill",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Airway Bill",
                    ),
                ),
                (
                    "pick_up",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pick up"
                    ),
                ),
                (
                    "customs",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Customs "
                    ),
                ),
                (
                    "sbl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SBL"
                    ),
                ),
                (
                    "other_charge",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Other Charge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Optional",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Agency"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Carrier"
                    ),
                ),
                (
                    "airfreight",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Airfreight"
                    ),
                ),
                (
                    "airway_bill",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Airway Bill",
                    ),
                ),
                (
                    "pick_up",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pick up"
                    ),
                ),
                (
                    "ordino",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ordino"
                    ),
                ),
                (
                    "customs",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Customs "
                    ),
                ),
                (
                    "warehouse_fee",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Warehouse Fee",
                    ),
                ),
                (
                    "document_under_our_compnay_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Document Under Our Compnay Name",
                    ),
                ),
                (
                    "other_charge",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Other Charge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                (
                    "total_buy",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Total Buy"
                    ),
                ),
                (
                    "total_sell",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Total Sell"
                    ),
                ),
                (
                    "profit",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Profit"
                    ),
                ),
                (
                    "base_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.baseform"
                    ),
                ),
                (
                    "mandatory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.mandatory"
                    ),
                ),
                (
                    "optional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="form.optional",
                    ),
                ),
            ],
        ),
    ]
