# Generated by Django 3.2 on 2021-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
