# Generated by Django 3.2 on 2021-05-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_auto_20210514_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="buy_mandatory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandatory_buy_form",
                to="form.mandatory",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="sell_mandatory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandatory_sell_form",
                to="form.mandatory",
            ),
        ),
    ]
