# Generated by Django 3.2 on 2021-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_auto_20210514_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="profit",
            field=models.IntegerField(blank=True, null=True, verbose_name="Profit"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_buy",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Buy"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_sell",
            field=models.IntegerField(blank=True, null=True, verbose_name="Total Sell"),
        ),
    ]
