# Generated by Django 3.2 on 2021-05-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0005_auto_20210514_1508"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseFormCourier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "consignee",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Consignee"
                    ),
                ),
                (
                    "company_invoice_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company Invoice No",
                    ),
                ),
                (
                    "consignee_order_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Consignee Order No",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Currency"
                    ),
                ),
                (
                    "AWB_no_first",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="AWB No First"
                    ),
                ),
                (
                    "AWB_no_second",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="AWB No Second"
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="To"
                    ),
                ),
                (
                    "from_in_base",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="From"
                    ),
                ),
                (
                    "number_of_shipment",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Shipment "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellBuyCourier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ups_fee",
                    models.IntegerField(blank=True, null=True, verbose_name="UPS Fee"),
                ),
                (
                    "fuel_surcharge_ups",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Fuel Surcharge UPS"
                    ),
                ),
                (
                    "eph_ups",
                    models.IntegerField(blank=True, null=True, verbose_name="EPH UPS"),
                ),
                (
                    "out_of_area_ups",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Out Of Area UPS"
                    ),
                ),
                (
                    "dhl_fee",
                    models.IntegerField(blank=True, null=True, verbose_name="DHL Fee"),
                ),
                (
                    "fuel_surcharge_dhl",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Fuel Surcharge DHL"
                    ),
                ),
                (
                    "eph_dhl",
                    models.IntegerField(blank=True, null=True, verbose_name="EPH DHL"),
                ),
                (
                    "out_of_area_dhl",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Out Of Area DHL"
                    ),
                ),
                (
                    "aramex_fee",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Aramex Fee"
                    ),
                ),
                (
                    "domestic_transfer_ups",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Domestic Transfer UPS"
                    ),
                ),
                (
                    "eph_domestic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="EPH Domestic"
                    ),
                ),
                (
                    "tax_for_domestic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="TAX For Domestic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "total_buy",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Buy"
                    ),
                ),
                (
                    "total_sell",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Sell"
                    ),
                ),
                (
                    "custom_clearnace_buy",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Custom Clearnace Buy"
                    ),
                ),
                (
                    "custom_clearnace_sell",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Custom Clearnace Sell"
                    ),
                ),
                (
                    "profit_sell",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Profit Sell"
                    ),
                ),
                (
                    "profit",
                    models.IntegerField(blank=True, null=True, verbose_name="Profit"),
                ),
                (
                    "base_form_courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.baseformcourier",
                    ),
                ),
                (
                    "buy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_form",
                        to="form.sellbuycourier",
                    ),
                ),
                (
                    "sell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_form",
                        to="form.sellbuycourier",
                    ),
                ),
            ],
        ),
    ]
