# Generated by Django 3.2 on 2021-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_auto_20210518_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="buy_cost",
            field=models.IntegerField(blank=True, null=True, verbose_name="Buy_Cost"),
        ),
        migrations.AddField(
            model_name="courier",
            name="sell_cost_prof",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Sell_Cost_Prof"
            ),
        ),
    ]
