# Generated by Django 3.2 on 2021-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20210528_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbuycourier',
            name='eph_ups_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='EPH UPS Percentage'),
        ),
    ]
