# Generated by Django 3.2 on 2021-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_sellbuycourier_eph_ups_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatory',
            name='other_charge_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Charge Name'),
        ),
        migrations.AddField(
            model_name='mandatory',
            name='other_charge_second',
            field=models.IntegerField(blank=True, null=True, verbose_name='Other Charge_second'),
        ),
        migrations.AddField(
            model_name='mandatory',
            name='other_charge_second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Charge Name Second'),
        ),
        migrations.AddField(
            model_name='optional',
            name='other_charge_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Charge Name'),
        ),
        migrations.AddField(
            model_name='optional',
            name='other_charge_second',
            field=models.IntegerField(blank=True, null=True, verbose_name='Other Charge_second'),
        ),
        migrations.AddField(
            model_name='optional',
            name='other_charge_second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Charge Name Second'),
        ),
    ]
