# Generated by Django 3.2 on 2021-06-14 21:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20210614_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_type', models.CharField(blank=True, choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number')),
            ],
        ),
    ]
