# Generated by Django 3.2 on 2021-06-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_consignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseformcourier',
            name='consignee',
        ),
    ]
