# Generated by Django 3.2 on 2021-06-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_baseformcourier_consignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseform',
            name='consignee',
        ),
    ]
