# Generated by Django 3.2 on 2021-06-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_remove_baseform_consignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.consignee'),
        ),
    ]
