# Generated by Django 3.2 on 2021-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_currency_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='charges',
        ),
        migrations.AddField(
            model_name='statement',
            name='charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
