# Generated by Django 3.2 on 2021-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_auto_20210617_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
