# Generated by Django 3.2 on 2021-06-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_statement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.consignee'),
        ),
        migrations.AddField(
            model_name='statement',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.courier'),
        ),
    ]
