# Generated by Django 3.2 on 2021-06-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_auto_20210617_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
