# Generated by Django 3.2 on 2021-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_alter_statement_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.AlterField(
            model_name='baseform',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('eur', 'eur'), ('try', 'try')], max_length=255, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='baseformcourier',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('eur', 'eur'), ('try', 'try')], max_length=255, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('eur', 'eur'), ('try', 'try')], max_length=255, null=True),
        ),
    ]
