# Generated by Django 3.2 on 2021-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_auto_20210617_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('date', models.DateField(verbose_name='Date')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('invoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice')),
                ('deposit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Deposit')),
                ('irr', models.CharField(blank=True, max_length=255, null=True, verbose_name='IRR')),
                ('try_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='TRY')),
                ('usd', models.CharField(blank=True, max_length=255, null=True, verbose_name='USD')),
                ('xe', models.CharField(blank=True, max_length=255, null=True, verbose_name='XE')),
            ],
        ),
    ]
