# Generated by Django 3.2 on 2021-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='balance',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='charge',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
