# Generated by Django 3.2 on 2021-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_auto_20210618_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Name'),
        ),
    ]
