# Generated by Django 3.1.2 on 2020-11-06 09:32

from django.db import migrations, models
import phonenumber_field.modelfields
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=utils.custom_fields.FarsiCharField(blank=True, max_length=40, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=utils.custom_fields.FarsiCharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text="A user with out this item can't use site features.", verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_validate',
            field=models.BooleanField(default=False, help_text="If a user's email is validate select this item if this item is not selected user should validate her/his email with verification email.", verbose_name='Is validate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
