# Generated by Django 2.0.2 on 2020-09-05 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
