# Generated by Django 3.1.2 on 2020-12-01 21:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201106_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(default='IR', max_length=2, verbose_name='Nationality'),
        ),
    ]
