# Generated by Django 2.0.2 on 2020-09-05 15:20

from django.db import migrations
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200905_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=utils.custom_fields.FarsiCharField(blank=True, error_messages={'max_length': 'This email has already been registered.'}, max_length=40, null=True, verbose_name='Company name'),
        ),
    ]
