# Generated by Django 2.0.2 on 2020-09-26 15:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200905_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
