# Generated by Django 3.1 on 2020-10-01 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models
import utils.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABoutUsHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('active', models.BooleanField(default=True, help_text='if you set this field true this information is shown in about us in home page', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'A bout us in home',
                'verbose_name_plural': 'All a bout us in home',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video_uploaded/')),
                ('active', models.BooleanField(default=True, help_text='if you set this field true this video is shown in home page', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video in home',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
            ],
            options={
                'verbose_name': 'News letter',
                'verbose_name_plural': 'All news letter',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('whats_app_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='enter phone number with country code like : +98... ', max_length=128, null=True, region=None, verbose_name='Whats app phone number')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('medium', models.URLField(blank=True, null=True, verbose_name='Medium')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('active', models.BooleanField(default=True, help_text='if you set this field true this information is shown in footer of pages', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Social network',
                'verbose_name_plural': 'Social networks in footer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ABoutUsHomeSlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='a_bout_us_home/', verbose_name='Image')),
                ('a_bout_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='home.aboutushome', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['-a_bout_us'],
            },
        ),
    ]
