# Generated by Django 2.0.2 on 2020-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='video_uploaded/')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video in home',
            },
        ),
    ]
