# Generated by Django 2.0.2 on 2020-09-26 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homevideo',
            options={'ordering': ['-date'], 'verbose_name': 'Video', 'verbose_name_plural': 'Video in home'},
        ),
        migrations.RenameField(
            model_name='homevideo',
            old_name='upload',
            new_name='video',
        ),
        migrations.AddField(
            model_name='homevideo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
