# Generated by Django 3.2 on 2021-04-28 20:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201106_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutushome',
            name='description_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian'),
        ),
        migrations.AddField(
            model_name='aboutushome',
            name='title_fa',
            field=utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='address_fa',
            field=utils.custom_fields.FarsiTextField(blank=True, null=True, verbose_name='Address Persian'),
        ),
        migrations.AlterField(
            model_name='aboutushomeslideshow',
            name='a_bout_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='home.aboutushome', verbose_name='A Bout Us'),
        ),
    ]
