# Generated by Django 2.0.2 on 2020-09-26 16:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200926_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABoutUsHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'A bout us in home',
                'verbose_name_plural': 'All a bout us in home',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ABoutUsHomeSlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='a_bout_us_home/', verbose_name='Image')),
                ('a_bout_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ABoutUsHome', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'A bout us picture in home',
                'verbose_name_plural': 'All a bout us pictures in home',
                'ordering': ['-a_bout_us'],
            },
        ),
    ]
