# Generated by Django 2.0.2 on 2020-09-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutushome_aboutushomeslideshow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutushomeslideshow',
            options={'ordering': ['-a_bout_us'], 'verbose_name': 'Picture', 'verbose_name_plural': 'All a bout us pictures in home'},
        ),
    ]
