# Generated by Django 2.0.2 on 2020-09-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200926_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutushomeslideshow',
            options={'ordering': ['-a_bout_us'], 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
    ]
