# Generated by Django 2.0.2 on 2020-09-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200926_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutushomeslideshow',
            name='a_bout_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='home.ABoutUsHome', verbose_name='Image'),
        ),
    ]
