# Generated by Django 2.0.2 on 2020-09-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alladdresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllAddresses',
            new_name='PublicNetwork',
        ),
        migrations.AlterModelOptions(
            name='publicnetwork',
            options={'ordering': ['-id'], 'verbose_name': 'Public network', 'verbose_name_plural': 'Public networks'},
        ),
    ]
