# Generated by Django 2.0.2 on 2020-09-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200926_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicnetwork',
            options={'ordering': ['-id'], 'verbose_name': 'Public network', 'verbose_name_plural': 'Public networks in footer'},
        ),
    ]
