# Generated by Django 2.0.2 on 2020-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200926_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicnetwork',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
    ]
