# Generated by Django 2.0.2 on 2020-09-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_publicnetwork_telegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-id'], 'verbose_name': 'News letter', 'verbose_name_plural': 'All news letter'},
        ),
    ]
