# Generated by Django 2.0.2 on 2020-09-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200926_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicNetwork',
            new_name='SocialNetwork',
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['-id'], 'verbose_name': 'Social network', 'verbose_name_plural': 'Social networks in footer'},
        ),
    ]
