# Generated by Django 2.0.2 on 2020-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200926_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
    ]
