# Generated by Django 3.2 on 2021-04-29 21:00

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import tinymce.models
import utils.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABoutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('title_fa', utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('description_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian')),
                ('image', models.ImageField(upload_to='a_bout_us/', verbose_name='Image')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('active', models.BooleanField(default=True, help_text='If you set this field true this information is shown in about us page.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us page',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', utils.custom_fields.FarsiCharField(max_length=60, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number')),
                ('message', models.TextField(verbose_name='Message')),
                ('check', models.BooleanField(default=False, verbose_name='Check')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': "User's messages from contact us",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('title_fa', utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('description_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('title_fa', utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('description_fa', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian')),
                ('image', models.ImageField(upload_to='service/', verbose_name='Image')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number')),
                ('address', utils.custom_fields.FarsiTextField(blank=True, null=True, verbose_name='Address')),
                ('address_fa', utils.custom_fields.FarsiTextField(blank=True, null=True, verbose_name='Address Persian')),
                ('map', models.TextField(blank=True, help_text='Enter iframe tag from google map.', null=True, verbose_name='Map')),
                ('active', models.BooleanField(default=True, help_text='If you set this field true this information is shown in support of about us page.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Support address',
                'verbose_name_plural': 'Support addresses',
                'ordering': ['-id'],
                'unique_together': {('email', 'phone_number')},
            },
        ),
    ]
