# Generated by Django 2.0.2 on 2020-08-31 12:02

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import utils.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', utils.custom_fields.FarsiCharField(max_length=60, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('description', utils.custom_fields.FarsiTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'AllNews',
                'ordering': ['-date'],
            },
        ),
    ]
