# Generated by Django 3.1.2 on 2020-11-06 09:32

from django.db import migrations, models
import phonenumber_field.modelfields
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['-id'], 'verbose_name': 'About us', 'verbose_name_plural': 'About us page'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='support',
            name='address',
            field=utils.custom_fields.FarsiTextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='support',
            name='map',
            field=models.TextField(blank=True, help_text='Enter iframe tag from google map.', null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='active',
            field=models.BooleanField(default=True, help_text='If you set this field true this information is shown in about us page.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='support',
            name='active',
            field=models.BooleanField(default=True, help_text='If you set this field true this information is shown in support of about us page.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='support',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
