# Generated by Django 3.2 on 2021-04-28 20:34

from django.db import migrations
import tinymce.models
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20201106_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_fa',
            field=utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fa',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description Persian'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fa',
            field=utils.custom_fields.FarsiCharField(blank=True, max_length=50, null=True, verbose_name='Title Persian'),
        ),
        migrations.AddField(
            model_name='support',
            name='address_fa',
            field=utils.custom_fields.FarsiTextField(blank=True, null=True, verbose_name='Address Persian'),
        ),
    ]
