# Generated by Django 2.0.2 on 2020-09-12 12:24

from django.db import migrations, models
import tinymce.models
import utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.custom_fields.FarsiCharField(max_length=50, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='service/', verbose_name='Image')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
