# Generated by Django 2.0.2 on 2020-09-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact us', 'verbose_name_plural': 'All Contact'},
        ),
    ]
