# Generated by Django 2.0.2 on 2020-09-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_auto_20200926_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'A bout us', 'verbose_name_plural': "All a bout us page's data"},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Message', 'verbose_name_plural': "User's messages from contact us"},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-date'], 'verbose_name': "Support's address", 'verbose_name_plural': "Support's addresses"},
        ),
    ]
