# Generated by Django 2.0.2 on 2020-09-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_auto_20200926_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News', 'verbose_name_plural': 'All news'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'News letter', 'verbose_name_plural': 'All news letter'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-date'], 'verbose_name': 'Support address', 'verbose_name_plural': 'Support addresses'},
        ),
    ]
