# Generated by Django 2.0.2 on 2020-09-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_auto_20200926_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
