# Generated by Django 2.0.2 on 2020-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_auto_20200926_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='a_bout_us/', verbose_name='Image'),
        ),
    ]
