# Generated by Django 2.0.2 on 2020-09-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_contactus_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-id'], 'verbose_name': 'Message', 'verbose_name_plural': "User's messages from contact us"},
        ),
    ]
