# Generated by Django 2.0.2 on 2020-09-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0016_aboutus_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['-id'], 'verbose_name': 'A bout us', 'verbose_name_plural': "All a bout us page's data"},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='date',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='active',
            field=models.BooleanField(default=True, help_text='if you set this field true this information is shown in about us page', verbose_name='Active'),
        ),
    ]
