# Generated by Django 2.0.2 on 2020-09-27 12:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0018_auto_20200927_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='support',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='enter phone number with country code like : +98... ', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
