# Generated by Django 2.0.2 on 2020-09-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_auto_20200927_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='support',
            unique_together={('email', 'phone_number')},
        ),
    ]
